buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {

  }
}
plugins {
    id 'application'
    id "com.google.protobuf" version "0.9.6"
}

version = '1.0'
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
ext {
    mainClassName = "com.lttldrgn.portochat.client.ClientLauncher"
}
application {
    mainClass = rootProject.ext.mainClassName
}

repositories {
    mavenCentral()
}
dependencies {
    implementation 'com.google.protobuf:protobuf-java:3.25.8'
}

protobuf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.25.8'
    }
}

task fullJar(type: Jar) {
	manifest {
        attributes 'Implementation-Title': 'Gradle Jar File',
            'Implementation-Version': archiveVersion,
            'Main-Class': rootProject.ext.mainClassName
    }
    archiveBaseName = 'Port-O-Chat'
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
//        exclude ""
    }
    with jar
}

task deploy(type: Copy, dependsOn:'build') {
    from 'src/logging.properties'
    from 'scripts'
    from 'build/libs/'
    into 'build/deploy/'
}

task debug(type: JavaExec) {
    debug = true
    classpath = sourceSets.main.runtimeClasspath
    mainClass = mainClassName
}

task runServer(type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.lttldrgn.portochat.server.ServerLauncher'
}

task debugServer(type: JavaExec) {
    debug = true
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.lttldrgn.portochat.server.ServerLauncher'
}

allprojects {
  tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
  }
}